[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/images/*"
  to = "/assets/images/:splat"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/assets/data/:splat"
  status = 200

[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"